# This rule is not used by the project watcher-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over watcher.openstack.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: watcher-operator
    app.kubernetes.io/managed-by: kustomize
  name: watcherapplier-admin-role
rules:
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherappliers
  verbs:
  - '*'
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherappliers/status
  verbs:
  - get
